name: asther_dev
services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    container_name: asther_postgre_dev
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: astheron
      POSTGRES_PASSWORD: supersmart
      POSTGRES_DB: asther
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U astheron -d asther"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
